### ISSUE TITLE
How to create xml file

### ISSUE THREAD

**Issue by rtomioka** [brendonw1/KilosortWrapper#6]
We recently involve kilosort&phy to do clustering. 
And realized that it is difficult to access each waveform with its outputs: rez file.
Therefore we would like to use your Kilosort2Neurosuite to extract spk.file.
As you described in the ConvertKilosort2Neurosuite_KSW.m, Kilosort2Neurosuite required two files: dat and xml. Now I stacked to run your Kilosort2Neurosuite, because I have no idea about xml.
If possible, could you please upload your program: makeProbeMapKlusta2.m

Thank you in advance.
Tomi

**Comment by petersenpeter** [comment]
Hi Tomi

Try the loadSpikes script, for extracting the spike sorted data from Phy into Matlab. The script will also load average waveforms. You can also try Phy2Neurosuite (will create the classic neurosuite files), but it requires some files created by the KilosortWrapper and some phy plugins I created. See all links below.

https://github.com/brendonw1/KilosortWrapper/blob/master/loadSpikes.m
https://github.com/brendonw1/KilosortWrapper/blob/master/Phy2Neurosuite.m
https://github.com/petersenpeter/phy1-plugins

/ Peter

**Comment by rtomioka** [comment]
Hi Peter,

Thank you for your quick reply.
Although I tried to extract waveforms using loadSpikes, I could not.  Because it might require xml file on the process. If I can get the info about xml, it might be the best solution. So far, I can not find it on the web. Do you know that?

Best,
Tomi

**Comment by brendonw1** [comment]
The xml is the same as is required for neuroscope.   You can google
neuroscope and download.  Neuroscope makes the xml in fact

**Comment by rtomioka** [comment]
Thank you very much for your kindness.

Best,
Tomi

**Comment by brendonw1** [comment]
You might consider also Kilosort2 - it is better than Kilosort(1)
