### ISSUE TITLE
Error: `Conversion to single from gpuArray is not possible.`

### ISSUE THREAD

**Issue by wuffi** [brendonw1/KilosortWrapper#8]
When running the function `Kilosort2Neurosuite(rez)`, MATLAB gives me the error message:
```
Conversion to single from gpuArray is not possible.
```

Trying to run  
```
W = gpuArray(rez.W)
```
gives me the rror message:
```
Error using message/getString
Unable to load a message catalog 'parallel:array'. Please check the file location and format.
```
Is this rather an issue of my `rez` data structure? Did I use wrong settings for KiloSort(2) to generate it?

I started the *KiloSort2* run manually (i.e. not by calling the `KiloSortWrapper` function) and used the default configuration of *KiloSort2* adapted for a recording with 32 channels.

When using the `KilosortConfiguration.m` file, everything works fine.
Therefore, I assume the intended usage is to call `KiloSortWrapper` in order to start *KiloSort* and then call `Kilosort2Neurosuite` on the output files generated by this run.

**Comment by petersenpeter** [comment]
Hi 

I don't have a direct answer to your question, but the kilosort wrapper was developed for Kilosort1. There is a new version that handles kilosort2: https://github.com/ThomasHainmueller/KilosortWrapper

**Comment by wuffi** [comment]
Hi Peter,

Thanks a lot for your hint. I wasn't aware that the KilosortWrapper was developed for KiloSort1.
I will try the version for KiloSort2.

**Comment by brendonw1** [comment]
Sweet
